/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main_Frame.java
 *
 * Created on 27.12.2011, 18:41:11
 */
package dok.view;

import dok.controller.actions.OpenPictureAction;
import dok.controller.actions.OpenPictureToCoverAction;
import dok.controller.actions.ProceedAction;
import dok.model.Model;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Tomas
 */
public class Main_Frame extends javax.swing.JFrame {

    private Model model;
    
    /** Creates new form Main_Frame */
    public Main_Frame(Model model) {
        this.model = model;
        jFileChooser = new JFileChooser("C:\\Users\\Public\\Pictures\\Sample Pictures");
        initComponents();
        setLocationRelativeTo(null);
        this.btnExtract.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWrittenImage = new javax.swing.JLabel();
        btnOpenImage = new javax.swing.JButton();
        txfImagePath = new javax.swing.JTextField();
        btnImageToCover = new javax.swing.JButton();
        txfCoverPath = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        btnProceed = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        lblCharCount = new javax.swing.JLabel();
        lblImageToWriteInto = new javax.swing.JLabel();
        btnExtract = new javax.swing.JButton();
        codeTextFileld = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DOK VAN431 Steganografia + DCT");

        lblWrittenImage.setBackground(new java.awt.Color(204, 204, 255));
        lblWrittenImage.setText("jLabel1");
        lblWrittenImage.setToolTipText("covered image");

        btnOpenImage.setText("nosny obrazok");

        btnImageToCover.setText("obrazok na zapis");

        jLabel2.setText("sprava na zapis:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setText("Status:");

        btnProceed.setText("proceed");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        lblCharCount.setText("max chars:");

        lblImageToWriteInto.setBackground(new java.awt.Color(204, 204, 255));
        lblImageToWriteInto.setText("jLabel1");
        lblImageToWriteInto.setToolTipText("image as medium");

        btnExtract.setText("Extract");

        codeTextFileld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codeTextFileldKeyPressed(evt);
            }
        });

        jLabel1.setText("Extrakcny kod:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImageToWriteInto, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWrittenImage, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(codeTextFileld, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnImageToCover, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(btnOpenImage, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(59, 59, 59)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfCoverPath, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(txfImagePath, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(lblCharCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnProceed, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExtract, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOpenImage)
                            .addComponent(txfImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnImageToCover)
                            .addComponent(txfCoverPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblCharCount, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3))
                    .addComponent(lblImageToWriteInto, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codeTextFileld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProceed)
                            .addComponent(btnExtract)))
                    .addComponent(lblWrittenImage, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void codeTextFileldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeTextFileldKeyPressed
        this.btnExtract.setEnabled((this.codeTextFileld.getText().length()>6));
}//GEN-LAST:event_codeTextFileldKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExtract;
    private javax.swing.JButton btnImageToCover;
    private javax.swing.JButton btnOpenImage;
    private javax.swing.JButton btnProceed;
    private javax.swing.JTextField codeTextFileld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblCharCount;
    private javax.swing.JLabel lblImageToWriteInto;
    private javax.swing.JLabel lblWrittenImage;
    private javax.swing.JTextField txfCoverPath;
    private javax.swing.JTextField txfImagePath;
    // End of variables declaration//GEN-END:variables

    private JFileChooser jFileChooser;

    public JFileChooser getjFileChooser() {
        return jFileChooser;
    }

    public void setjFileChooser(JFileChooser jFileChooser) {
        this.jFileChooser = jFileChooser;
    }

    public JLabel getLblImageToWriteInto() {
        return lblImageToWriteInto;
    }

    public void setLblImageToWriteInto(JLabel lblImageToWriteInto) {
        this.lblImageToWriteInto = lblImageToWriteInto;
    }

    public JLabel getLblWrittenImage() {
        return lblWrittenImage;
    }

    public void setLblWrittenImage(JLabel lblWrittenImage) {
        this.lblWrittenImage = lblWrittenImage;
    }

    public JButton getBtnOpenImage() {
        return btnOpenImage;
    }

    public void setBtnOpenImage(JButton btnOpenImage) {
        this.btnOpenImage = btnOpenImage;
    }

    public JTextArea getjTextArea1() {
        return jTextArea1;
    }

    public void setjTextArea1(JTextArea jTextArea1) {
        this.jTextArea1 = jTextArea1;
    }

    public JButton getBtnImageToCover() {
        return btnImageToCover;
    }

    public void setBtnImageToCover(JButton btnImageToCover) {
        this.btnImageToCover = btnImageToCover;
    }

    public JTextField getTxfCoverPath() {
        return txfCoverPath;
    }

    public void setTxfCoverPath(JTextField txfCoverPath) {
        this.txfCoverPath = txfCoverPath;
    }

    public JTextField getTxfImagePath() {
        return txfImagePath;
    }

    public void setTxfImagePath(JTextField txfImagePath) {
        this.txfImagePath = txfImagePath;
    }

    public JLabel getLblCharCount() {
        return lblCharCount;
    }

    public void setLblCharCount(JLabel lblCharCount) {
        this.lblCharCount = lblCharCount;
    }

    public JTextField getCodeTextFileld() {
        return codeTextFileld;
    }

    public void setCodeTextFileld(JTextField codeTextFileld) {
        this.codeTextFileld = codeTextFileld;
    }
    
    
    
    public void AddOpenPictureAction(OpenPictureAction openPictureAction) {
        this.btnOpenImage.addActionListener(openPictureAction);
    }

    public void AddProceedActionListener(ProceedAction proceedAction) {
        btnProceed.addActionListener(proceedAction);
    }

    public void AddOpenPictureToCoverAction(OpenPictureToCoverAction openPictureToCoverAction) {
        this.btnImageToCover.addActionListener(openPictureToCoverAction);
    }

    public JButton getBtnExtract() {
        return btnExtract;
    }

    public void setBtnExtract(JButton btnExtract) {
        this.btnExtract = btnExtract;
    }

    public JList getjList1() {
        return jList1;
    }

    public void setjList1(JList jList1) {
        this.jList1 = jList1;
    }
    
    
}
